# This workflow will install dependencies, create coverage tests and run Jest Coverage Comment
# For more information see: https://github.com/MishaKav/jest-coverage-comment/
name: Test Coverage Comment
on:
  pull_request:
    branches:
      - main
    type:
      - opened
      - synchronize
      - reopened

  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: |
          npx c8 npm test -- --coverage ./coverage --coverageReporters="json-summary"

      - name: List files
        run: cd coverage && ls -la

      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@main